"""empty message

Revision ID: 616f3397f4dc
Revises: a7d22b69c34e
Create Date: 2020-10-07 04:32:40.614948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616f3397f4dc'
down_revision = 'a7d22b69c34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_column('Show', 'venue_id')
    # ### end Alembic commands ###
